const siteData = [
	{
		"name": "South Benton",
		"location": "2064 Klocko Wall",
		"description": "Ea sapiente distinctio enim nihil.",
		"price": "6",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: false",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Breitenbergview",
		"location": "08976 Lowe Rue",
		"description": "Alias amet qui omnis voluptatem.",
		"price": "30",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: false",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: false",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Merced",
		"location": "1219 Bailey Corners",
		"description": "Natus iusto necessitatibus est sequi.",
		"price": "48",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: false",
			"trash: true",
			"hotTub: false",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Kreigerstad",
		"location": "42744 Gabriella Stravenue",
		"description": "Quia officia consequatur tempora omnis.",
		"price": "39",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: false",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Shannaport",
		"location": "4679 Kassulke Path",
		"description": "Tenetur facilis quasi magnam adipisci.",
		"price": "21",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: false",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "North Keltonboro",
		"location": "9176 Larkin Hollow",
		"description": "Facilis aliquid perspiciatis consequuntur quia.",
		"price": "47",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: false",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Mckenziehaven",
		"location": "346 Feest Trail",
		"description": "Sunt ut at corporis nobis.",
		"price": "41",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: true",
			"boating: false",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "O'Haramouth",
		"location": "13971 Katlynn Views",
		"description": "Dolor suscipit ut dolor deserunt.",
		"price": "38",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Howeview",
		"location": "256 Balistreri Divide",
		"description": "Est et ab laudantium quia.",
		"price": "6",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: false",
			"campfire: false",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: false",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Holdenstad",
		"location": "5545 Effertz Lights",
		"description": "Repellat soluta aut accusantium dolorem.",
		"price": "26",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: false",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Port Arnoldoshire",
		"location": "66546 Cedrick Forks",
		"description": "Enim earum earum voluptatem exercitationem.",
		"price": "22",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: false",
			"showers: false",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Marysville",
		"location": "5253 Tatyana Crest",
		"description": "Quia et possimus pariatur quis.",
		"price": "8",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Euless",
		"location": "35728 Maggio Unions",
		"description": "Eaque sed expedita accusantium rem.",
		"price": "12",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Revere",
		"location": "3263 White Prairie",
		"description": "Expedita facere eum sed rerum.",
		"price": "22",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: false",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "South Hill",
		"location": "17891 Little Glen",
		"description": "Iste sunt tenetur similique debitis.",
		"price": "20",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: false",
			"toilets: false",
			"campfire: false",
			"water: false",
			"showers: false",
			"trash: false",
			"hotTub: false",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: false",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Borershire",
		"location": "601 Corkery Unions",
		"description": "Recusandae molestiae dolor assumenda sint.",
		"price": "44",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "North Ernestineville",
		"location": "99143 Bernard Underpass",
		"description": "Quisquam hic eum culpa eaque.",
		"price": "24",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Kenosha",
		"location": "7287 Erdman Trail",
		"description": "Et optio quas natus praesentium.",
		"price": "22",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Braxtonport",
		"location": "4737 Ullrich Drive",
		"description": "Similique nihil facere optio commodi.",
		"price": "40",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: false",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Redding",
		"location": "391 Desiree Inlet",
		"description": "Illum illo cum dicta nam.",
		"price": "46",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: false",
			"water: false",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Tyler",
		"location": "4592 Feil Underpass",
		"description": "Optio placeat alias nobis laborum.",
		"price": "3",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: false",
			"water: false",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: true",
			"boating: false",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Narcisoberg",
		"location": "08024 Kale Crossroad",
		"description": "Voluptatem placeat est debitis perspiciatis.",
		"price": "9",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: false",
			"campfire: false",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Sebastianchester",
		"location": "72610 Shayna Rapids",
		"description": "Tempore illo culpa repellendus et.",
		"price": "17",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: false",
			"trash: false",
			"hotTub: false",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "South Luna",
		"location": "27357 Zora Forest",
		"description": "Est nobis sit nihil ex.",
		"price": "37",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Amandaborough",
		"location": "4841 Denesik Hill",
		"description": "Eligendi ut est et dolor.",
		"price": "7",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: false",
			"water: false",
			"showers: false",
			"trash: false",
			"hotTub: false",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "South Neha",
		"location": "5666 Myrtle Shores",
		"description": "Rem voluptas omnis quasi tenetur.",
		"price": "31",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: false",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Walkerchester",
		"location": "25312 Barton Camp",
		"description": "Et et perferendis quia est.",
		"price": "35",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Frankiefurt",
		"location": "3453 Marc Oval",
		"description": "Atque quia rerum non ipsam.",
		"price": "40",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: false",
			"trash: true",
			"hotTub: false",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: false",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Bakersfield",
		"location": "30920 Keven Mall",
		"description": "Nobis quos harum non est.",
		"price": "5",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Chestertown",
		"location": "465 Ebba Street",
		"description": "Magni eos ullam praesentium incidunt.",
		"price": "29",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Lake Berneicehaven",
		"location": "6142 Hartmann Forges",
		"description": "Neque repudiandae velit et beatae.",
		"price": "8",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "East Greyson",
		"location": "6353 Weissnat Mountain",
		"description": "Aut eius consectetur et sunt.",
		"price": "10",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: false",
			"campfire: false",
			"water: true",
			"showers: false",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: false",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Alhambra",
		"location": "750 Claudie Club",
		"description": "Voluptates dolore consequuntur aut distinctio.",
		"price": "28",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Homenickworth",
		"location": "9074 Nitzsche Underpass",
		"description": "Quae minima minus nostrum error.",
		"price": "44",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: false",
			"toilets: false",
			"campfire: false",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: false",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: false",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Dallas",
		"location": "9916 Sadye Park",
		"description": "Cum voluptas voluptate explicabo ipsum.",
		"price": "37",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: false",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "East Hailee",
		"location": "34062 Dayana Isle",
		"description": "Quam consequuntur vel beatae aut.",
		"price": "11",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Tyriqueville",
		"location": "0919 Koss Streets",
		"description": "Eos voluptatem id ratione alias.",
		"price": "13",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Delmerfort",
		"location": "6498 Jodie Corner",
		"description": "Quod qui dolores rerum est.",
		"price": "3",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: false",
			"trash: false",
			"hotTub: false",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: false",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Caguas",
		"location": "252 Runte Islands",
		"description": "Quasi placeat et officia explicabo.",
		"price": "14",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Port Wendellside",
		"location": "22651 Geovany Valleys",
		"description": "Aut minima nobis commodi consequuntur.",
		"price": "36",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: false",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Kaileyboro",
		"location": "3497 Emory Circle",
		"description": "Exercitationem enim et est quibusdam.",
		"price": "50",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Santee",
		"location": "6351 Howell Summit",
		"description": "Temporibus ea consequuntur dolorem et.",
		"price": "24",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: false",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: false",
			"boating: true",
			"offRoading: true",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "South Jerrellhaven",
		"location": "32604 Fahey Fall",
		"description": "Aut quia quod officiis eveniet.",
		"price": "30",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: false",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Port Orange",
		"location": "497 Becker Ford",
		"description": "Nostrum qui impedit consequatur vel.",
		"price": "45",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: false",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Port Cody",
		"location": "64689 Samantha Overpass",
		"description": "Sint vel provident placeat consequatur.",
		"price": "1",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Luzville",
		"location": "0454 Rhett Run",
		"description": "Illo nulla quo laboriosam autem.",
		"price": "38",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: false",
			"boating: true",
			"offRoading: true",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Port Chazview",
		"location": "1596 Guiseppe Junctions",
		"description": "Assumenda expedita illo molestiae asperiores.",
		"price": "39",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: false",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Port Bria",
		"location": "15915 Lueilwitz Burg",
		"description": "Et saepe voluptas qui illo.",
		"price": "26",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Birmingham",
		"location": "713 Johnston Streets",
		"description": "Nemo error eligendi non recusandae.",
		"price": "41",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "East Adeletown",
		"location": "81279 Laury Parkway",
		"description": "Qui et ipsam perferendis beatae.",
		"price": "20",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: false",
			"water: true",
			"showers: false",
			"trash: false",
			"hotTub: true",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	}
]

export default siteData;